---
- name: Install MySQL on CentOS
  hosts: 172.16.0.194
  become: yes
  tasks:
    - name: Install MySQL Server
      yum:
        name: mysql-server
        state: present

    - name: Start MySQL Service
      service:
        name: mysqld
        state: started
        enabled: yes
